### DISCUSSION TITLE
MQTT publish message

### DISCUSSION THREAD

**Discussion by martin8310** [syssi/esphome-atorch-dl24#37] [General]
Hello,

I'm happy with that tool, really great work. 

But I have two questions:
1. Is it possible to add also the external temperature sensor (NTC) information?
2. How can I publish a MQTT command to reset all the values on the dl24? The standard subscribe topic looks like that "dl24_last/sensor/dl24_last_spannung/state"

Regards 
Martin

**Comment by syssi** [comment]
1. Unfortunately the measurement of the external temperature sensor isn't part of the BLE notification payload.
2.  The standard button topic should look like this: `device_topic/button/button_id/command`. You have to publish the message "PRESS" there. The node should pick up the message and press the selected button entity.

**Comment by martin8310** [comment]
Hi,

unfortunately "dl24_last/button/reset_all/command" payload: PRESS dosn't work. Do you have an example for me?

**Reply by syssi** [reply]
Could you give it another try using the payload "press" instead? :-)

**Reply by martin8310** [reply]
"press" dosn't work also

**Reply by syssi** [reply]
Could you provide your configuration yaml? I assume the `button_id` isn't correct.

**Reply by martin8310** [reply]
It is your original config

**Reply by syssi** [reply]
If it's the original config, what's the name of your node? The name is part of the `button_id`.

**Reply by syssi** [reply]
F.e. this is some traffic:

```
basement-btle-gateway/sensor/basement-btle-gateway_dim_backlight/state 60
basement-btle-gateway/sensor/basement-btle-gateway_voltage/state 0.00
basement-btle-gateway/sensor/basement-btle-gateway_current/state 0.000
basement-btle-gateway/sensor/basement-btle-gateway_power/state 0.0000
basement-btle-gateway/sensor/basement-btle-gateway_capacity/state 0.000
basement-btle-gateway/sensor/basement-btle-gateway_energy/state 0
basement-btle-gateway/sensor/basement-btle-gateway_temperature/state 22
basement-btle-gateway/sensor/basement-btle-gateway_runtime_formatted/state (null)
basement-btle-gateway/sensor/basement-btle-gateway_dim_backlight/state 60
```

The name of my node is `basement-btle-gateway`. The prefix of the `button_id` is `basement-btle-gateway` too. In your case it's `dl24_last` I guess.

**Reply by syssi** [reply]
This is working for me:

```
mosquitto_pub -t 'basement-btle-gateway/button/basement-btle-gateway_reset_all/command' -m 'PRESS'
```

Please try

```
mosquitto_pub -t 'dl24_last/button/dl24_last_reset_all/command' -m 'PRESS'
```

**Comment by martin8310** [comment]
```
substitutions:
  name: dl24_last
  external_components_source: github://syssi/esphome-atorch-dl24@main
  dl24_mac_address: AB:0C:26:XX:XX:XX
  project_version: 1.2.0
  device_description: "Monitor and control a Atorch DL24 meter via bluetooth"

esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "syssi.esphome-atorch-dl24"
    version: ${project_version}

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf
    version: latest

external_components:
  - source: ${external_components_source}
    refresh: 0s

wifi:
  ssid: -
  password: -

ota:
logger:

mqtt:
  broker: 192.168.1.3
  #username: !secret mqtt_username
  #password: !secret mqtt_password
  id: mqtt_client

esp32_ble_tracker:

ble_client:
  - mac_address: ${dl24_mac_address}
    id: ble_client0

atorch_dl24:
  - id: atorch0
    ble_client_id: ble_client0
    check_crc: true
    # The meter publishes a status report per second via BLE notification. If you don't like this update interval
    # you can use this setting to throttle the sensor updates by skipping some status reports.
    throttle: 0s

binary_sensor:
  - platform: atorch_dl24
    atorch_dl24_id: atorch0
    running:
      name: "${name} running"

sensor:
  - platform: atorch_dl24
    atorch_dl24_id: atorch0
    voltage:
      name: "${name} spannung"
    current:
      name: "${name} strom"
    power:
      name: "${name} poweroutrt"
    capacity:
      name: "${name} kapazitaet "
    energy:
      name: "${name} energie"
    temperature:
      name: "${name} temperatur"
    dim_backlight:
      name: "${name} dim backlight"
    frequency:
      name: "${name} frequency"
    power_factor:
      name: "${name} power_factor"
    price_per_kwh:
      name: "${name} price per kwh"
    runtime:
      name: "${name} laufzeit"

text_sensor:
  - platform: atorch_dl24
    atorch_dl24_id: atorch0
    runtime_formatted:
      name: "${name} laufzeit lesbar"

button:
  - platform: atorch_dl24
    atorch_dl24_id: atorch0
    reset_energy:
      name: "${name} reset energy"
    reset_capacity:
      name: "${name} reset capacity"
    reset_runtime:
      name: "${name} reset runtime"
    reset_all:
      name: "${name} reset all"
    plus:
      name: "${name} plus"
    minus:
      name: "${name} minus"
    setup:
      name: "${name} setup"
    enter:
      name: "${name} enter"
```
