### ISSUE TITLE
increase precision on values

### ISSUE THREAD

**Issue by quilmore** [syssi/esphome-atorch-dl24#66]
hi
great code, worked first time!
may I ask to have a way to deal with precision? for example, Voltage in my case is shown as #.## but the measured only changes every 0.1 (like it will show 3.2 for all voltages between 3.20 and 3.29)
for comparison the e_test app on android shows 4 digits of precision, do I need to do something to have it the same way on this? thanks

**Comment by quilmore** [comment]
>  4 digits of precision
correction: it's 3 digits in the format ##.###

**Comment by syssi** [comment]
Could you provide a screenshot? Is the last digit always zero?

**Comment by syssi** [comment]
Could you increase the log level and provide some payload examples of your device?

```
logger:
  baud_rate: 0
  level: VERY_VERBOSE
  logs:
    api.service: WARN
    ota: WARN
    wifi: WARN
    sensor: DEBUG
```

Which model do you own?
