### ISSUE TITLE
DL24 Ströme in A, Positive & Negative Current Werte 

### ISSUE THREAD

**Issue by murdock1982** [syssi/esphome-atorch-dl24#73]
Ist es möglich die Ströme beim entladen den Wert mit einem negativen Vorzeichen zu erhalten? Dies würde Berechnungen ermöglichen.

**Comment by syssi** [comment]
You could add a `filter` to multiple the measurement by `-1` to invert the sign:

```
sensor:
  - platform: atorch_dl24
    atorch_dl24_id: atorch0
    voltage:
      name: "${name} voltage"
    current:
      name: "${name} current"
      filters:
        - multiply: -1.0
```

The DL24 isn't able to measure the direction of the flow direction.

**Comment by murdock1982** [comment]
The DT24 TW shows on the display whether loading or whether it is unloaded. So he can differentiate in which direction the streams go. Can you also use this information via ESP? Then exactly calculations would be possible.

Thank you very much for the quick answer and a nice day.

**Comment by syssi** [comment]
Thanks for the clarification! At the moment the 3 bytes are interpreted as unsigned integer:

https://github.com/syssi/esphome-atorch-dl24/blob/main/docs/protocol-design.md#dc-meter-report
https://github.com/syssi/esphome-atorch-dl24/blob/main/components/atorch_dl24/atorch_dl24.cpp#L304-L306

Could you increase the log level

```
logger:
  baud_rate: 0
  level: VERY_VERBOSE
  logs:
    api.service: WARN
    ota: WARN
    wifi: WARN
    sensor: DEBUG
```

And provide some logs with the RAW traffic (BLE notifications) while pushing current to the device?

**Comment by syssi** [comment]
Do you use the ESPHome Dashboard via Home Assistant or how do you update your ESPHome devices? If you use the dashboard the is a `LOG` button per device tile. You should see log messages starting with

```
Notification received: ...
```

here. These are the log messages I'm interested in.

**Comment by murdock1982** [comment]
I get the following in the LOGs:

INFO ESPHome 2023.12.5
INFO Reading configuration /config/esphome/solar01-dc-meter.yaml...
INFO Updating https://github.com/syssi/esphome-atorch-dl24.git@main
INFO UART logging is disabled (baud_rate=0). Not starting UART logs.

**Comment by syssi** [comment]
If you read the log using a serial connection instead of over-the-air this line (`baud_rate: 0`) needs to be removed:

```
logger:
  level: VERY_VERBOSE
  logs:
    api.service: WARN
    ota: WARN
    wifi: WARN
    sensor: DEBUG
```

Please try again!
