### ISSUE TITLE
No BLE connection on DL24M Purple

### ISSUE THREAD

**Issue by Viper7000** [syssi/esphome-atorch-dl24#76]
I have such a device https://www.aliexpress.com/item/1005004042609941.html
Firmware v 2.1
I have ESP32-CAM - that's all I have in stock
I use   framework: type: esp-idf. And I not see ble_client: connected. Instead I only see in the logs "[V][esp32_ble:314]: (BLE) gap_event_handler - 3"

```
[18:00:37][V][esp32_ble:314]: (BLE) gap_event_handler - 3
[18:00:37][V][esp32_ble:314]: (BLE) gap_event_handler - 3
[18:00:38][V][esp32_ble:314]: (BLE) gap_event_handler - 3
[18:00:38][V][esp32_ble:314]: (BLE) gap_event_handler - 3
[18:00:39][V][esp32_ble:314]: (BLE) gap_event_handler - 3
[18:00:39][V][esp32_ble:314]: (BLE) gap_event_handler - 3
[18:00:39][V][esp32_ble:314]: (BLE) gap_event_handler - 3
[18:00:39][V][esp32_ble:314]: (BLE) gap_event_handler - 3
[18:00:40][V][esp32_ble:314]: (BLE) gap_event_handler - 3
[18:00:40][V][esp32_ble:314]: (BLE) gap_event_handler - 3
[18:00:41][V][esp32_ble:314]: (BLE) gap_event_handler - 3
[18:00:41][V][esp32_ble:314]: (BLE) gap_event_handler - 3
[18:00:41][V][esp32_ble:314]: (BLE) gap_event_handler - 3
```

I can connect from PC and from mobile.

what could be wrong?

**Comment by syssi** [comment]
Please increase the log level and provide a complete log:

```
logger:
  level: VERY_VERBOSE
  logs:
    ota: INFO
    wifi: INFO
    scheduler: DEBUG
    component: DEBUG
    sensor: DEBUG
    mqtt: INFO
    mqtt.idf: INFO
    mqtt.component: INFO
    mqtt.sensor: INFO
    mqtt.switch: INFO
    api.service: INFO
    api: INFO
```

**Comment by Viper7000** [comment]
I'll definitely do it tomorrow. The power just went out throughout the city.
There is nothing interesting in the logs other than what I wrote above :)
Sees other BLEs, but there is no DL24M among them

**Comment by syssi** [comment]
I'm interested of the BLE advertisement of your DL24M. May be the service UUIDs / BLE module has changed slightly.

**Comment by Viper7000** [comment]
My config
```
substitutions:
  name: DL24M
  external_components_source: github://syssi/esphome-atorch-dl24@main
  dl24_mac_address: 4B:34:33:EB:92:8D
  project_version: 2.0.0
  device_description: "Monitor and control a Atorch meter via bluetooth"

esphome:
  name: atorch-dl24m
  friendly_name: Atorch-DL24M
  comment: ${device_description}
  project:
    name: "syssi.esphome-atorch-dl24"
    version: ${project_version}

esp32:
  board: esp32dev
  framework:
    type: esp-idf

external_components:
  - source: ${external_components_source}
    refresh: 0s

# Enable logging
logger:
  level: DEBUG
    
debug:
  update_interval: 5s

wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: !secret wifi_ssid2
    password: !secret wifi_password2

captive_portal:

esp32_ble_tracker:

ble_client:
  - mac_address: ${dl24_mac_address}
    id: ble_client0

atorch_dl24:
  - id: atorch0
    ble_client_id: ble_client0
    check_crc: false
    # The meter publishes a status report per second via BLE notification. If you don't like this update interval
    # you can use this setting to throttle the sensor updates by skipping some status reports.
    throttle: 0s

binary_sensor:
  - platform: atorch_dl24
    atorch_dl24_id: atorch0
    running:
      name: "${name} running"

sensor:
  - platform: uptime
    name: ESP32 Uptime
    filters:
      - lambda: return x / 3600.0;
    unit_of_measurement: h
    accuracy_decimals: 1
  - platform: wifi_signal
    name: ESP32 RSSI
    update_interval: 300s  
  - platform: esp32_hall
    name: "ESP32 Hall Sensor"
    update_interval: 300s
    entity_category: "diagnostic"
  - platform: debug
    free:
      name: "Heap Free"
    loop_time:
      name: "Loop Time"

  - platform: atorch_dl24
    atorch_dl24_id: atorch0
    voltage:
      name: "${name} voltage"
    current:
      name: "${name} current"
    power:
      name: "${name} power"
    capacity:
      name: "${name} capacity"
    energy:
      name: "${name} energy"
    temperature:
      name: "${name} temperature"
    dim_backlight:
      name: "${name} dim backlight"
    runtime:
      name: "${name} runtime"

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"
  - platform: wifi_info
    ip_address:
      name: ESP32 IP Address
    ssid:
      name: ESP32 SSID

  - platform: atorch_dl24
    atorch_dl24_id: atorch0
    runtime_formatted:
      name: "${name} runtime formatted"

button:
  - platform: atorch_dl24
    atorch_dl24_id: atorch0
    reset_energy:
      name: "${name} reset energy"
    reset_capacity:
      name: "${name} reset capacity"
    reset_runtime:
      name: "${name} reset runtime"
    reset_all:
      name: "${name} reset all"
    plus:
      name: "${name} plus"
    minus:
      name: "${name} minus"
    setup:
      name: "${name} setup"
    enter:
      name: "${name} enter"
```

**Comment by syssi** [comment]
Please replace

```
logger:
  level: DEBUG
```

with

```
logger:
  level: VERY_VERBOSE
  logs:
    ota: INFO
    wifi: INFO
    scheduler: DEBUG
    component: DEBUG
    sensor: DEBUG
    mqtt: INFO
    mqtt.idf: INFO
    mqtt.component: INFO
    mqtt.sensor: INFO
    mqtt.switch: INFO
    api.service: INFO
    api: INFO
```
