### ISSUE TITLE
Calculate Energy on the fly?

### ISSUE THREAD

**Issue by makerwolf1** [syssi/esphome-atorch-dl24#82]
Hey! Thanks for your great work, it adds massive value to the electronic load! 

The DL24 seems to only report energy in 10wH steps, despite displaying it with 3 digits accuracy on the display. Since we have both voltage and current it would be trivial to calculate energy on the fly, but unfortunately there is no way to add a `on_value:` hook to the sensors to trigger update of a template sensor. 

Any chance to maybe add that as an additional sensor to the platform?

**Comment by syssi** [comment]
The `on_value` automations are supported by every sensor entity. Please try something like this:

```
sensor:
  - platform: template
    id: power_computed
    name: "${name} power computed"
    update_interval: never

  - platform: atorch_dl24
    atorch_dl24_id: atorch0
    voltage:
      name: "${name} voltage"
      id: voltage
    current:
      name: "${name} current"
      id: current
      on_value:
        then:
          - sensor.template.publish:
              id: power_computed
              state: !lambda 'return id(voltage).state * id(current).state;'
```
